
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            America/Mexico_City # eg. Asia/Kathmandu
locale:              es_mx # eg. en_us
name:				         Blog
title:               Arturo Villa
tagline:             'Blog'
description:         'Blog sobre m√∫sica'
url:                 blog.arturovilla.com.mx
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              15khz # get it on https://disqus.com/admin/

author:
  name:           	 Arturo Villa
  url:            	 your site url
  facebook:          username
  twitter:           Arturo_vmtz
  google_plus:       username
  linkedin:          username

  pinterest:         username


fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
